### PR TITLE
Fix: add time to error screen.

### LINKED ISSUE #1805: Show current date and time in user error screens
In error screen like this: 

Image

please add the datetime to the data fields on the bottom.

Currently, it's hard to find a specific issue if we don't know when the user encountered the error.

### PR DESCRIPTION
**Pull request by kayjoosten**
Its hard to find errors in the logs without a timestamp as we dont know when the error occured. This is something we want to help the support department. Therefore, the time the screen appeard should have a iso timestamp.

page-2026-03-06T10-07-33-508Z

### CODE REVIEW

File: library/EngineBlock/ApplicationSingleton.php [hunk 1]
```diff
@@ -243,6 +243,12 @@ public function collectFeedbackInfo(Throwable $exception)
         }
 
         $feedbackInfo = array();
+        $feedbackInfo['datetime'] = (new DateTime())->format(DateTimeInterface::ATOM);
+        $requestUri = $_SERVER['REQUEST_URI'] ?? '';
+        $urlWithoutQuery = strtok($requestUri, '?');
+        $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
+        $host = $_SERVER['HTTP_HOST'] ?? '';
+        $feedbackInfo['requestUrl'] = $host ? $scheme . '://' . $host . $urlWithoutQuery : $urlWithoutQuery;
```
Comment (johanib) [inline library/EngineBlock/ApplicationSingleton.php]: Maybe better use `$request->getSchemeAndHttpHost()` as it takes the trusted_hosts config into consideration

**Review by johanib — APPROVED** [review]
Image

Image
