### PR TITLE
fix: return HTTP 503 on bootstrap error for /health endpoint

### LINKED ISSUE #1936: `/health` endpoint return 200 status even if the call fails
For example:
```
> curl -v http://172.18.0.15:80/health
*   Trying 172.18.0.15:80...
* Connected to 172.18.0.15 (172.18.0.15) port 80 (#0)
> GET /health HTTP/1.1
> Host: 172.18.0.15
> User-Agent: curl/7.88.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 12 Mar 2026 11:34:31 GMT
< Server: Apache
< X-Content-Type-Options: nosniff
< Vary: Accept-Encoding
< Content-Length: 251
< Content-Type: text/html; charset=UTF-8
<
<br />
<b>Fatal error</b>:  Uncaught RuntimeException: APP_SECRET must be at least 32 characters long in production. in /var/www/html/public/index.php:17
Stack trace:
#0 {main}
  thrown in <b>/var/www/html/public/index.php</b> on line <b>17</b><br />
* Connection #0 to host 172.18.0.15 left intact
```
Instead, return http status 500 on error.

### PR DESCRIPTION
**Pull request by kayjoosten**
## Summary

- Wraps the env validation block in `public/index.php` in a `try-catch(\Throwable)` so misconfiguration errors (e.g. missing/short `APP_SECRET`) return HTTP 503 instead of a PHP fatal error page with HTTP 200
- Response format matches the `openconext/monitor-bundle` DOWN convention: `{"status":"DOWN","message":"..."}` 
- Adds `error_log()` so bootstrap failures still appear in server logs
- Adds functional test coverage for the public `/health` route

## Test Plan

- [ ] Set `APP_ENV=prod` and `APP_SECRET=short` in devconf `.env`, restart engine container, hit `GET https://engine.dev.openconext.local/health` — expect HTTP 503 with `{"status":"DOWN","message":"APP_SECRET must be at least 32 characters long in production."}`
- [ ] Revert `.env`, restart, hit `/health` again — expect HTTP 200 `{"status":"UP"}`
- [ ] Run `./vendor/bin/phpunit --configuration=./tests/phpunit.xml --testsuite=functional --filter=MonitorControllerTest` — expect 3 tests passing

Closes #1936

### CODE REVIEW

File: public/index.php
Comment (johanib) [inline public/index.php]: Maybe include everything up to and including `Request::createFromGlobals()` into the try?
Wdyt?

**Review by johanib — COMMENTED** [review]
Did some digging. Your change seems the best solution 👍 
Not really nice or elegant. But it works and I think its the only way. 

One suggestion in the code, and maybe it's a good idea to also intercept errors in the regular fallback handler. Otherwise, in some scenario's the fallback might hijack errors, and do a 301 redirect instead of returning a 500 on the health endpoints..

```patch
Index: src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php b/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php
--- a/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php	(revision 1cdd470e6c39b94a9a7344e3a471010344487772)
+++ b/src/OpenConext/EngineBlockBundle/EventListener/FallbackExceptionListener.php	(date 1775571383912)
@@ -21,6 +21,7 @@
 use EngineBlock_Exception;
 use OpenConext\EngineBlockBridge\ErrorReporter;
 use Psr\Log\LoggerInterface;
+use Symfony\Component\HttpFoundation\JsonResponse;
 use Symfony\Component\HttpFoundation\RedirectResponse;
 use Symfony\Component\HttpKernel\Event\ExceptionEvent;
 use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
@@ -76,6 +77,15 @@
             $exception->getMessage()
         ));
 
+        $path = $event->getRequest()->getPathInfo();
+        if (in_array($path, ['/health', '/internal/health', '/info', '/internal/info'], true)) {
+            $event->setResponse(new JsonResponse(
+                ['status' => 'DOWN', 'message' => $exception->getMessage()],
+                JsonResponse::HTTP_SERVICE_UNAVAILABLE
+            ));
+            return;
+        }
+
         if ($exception instanceof EngineBlock_Exception) {
             $this->errorReporter->reportError($exception, 'Caught Unhandled EngineBlock_Exception');
         } else {
```

**Review by johanib — APPROVED** [review]
